# Project information
site_name: Dominio Público
site_author: Grupo 4
site_description: >-
  Documentação para do projeto de avaliação de interface do site Dominio Publico realizado na disciplina de Interação Humano Computador na Universidade de Brasília


# Repository
repo_url: https://github.com/Interacao-Humano-Computador/2023.2-Dominio-Publico
repo_name: 2023.2-dominio-publico


# Configuration
docs_dir: docs
theme: 
  name: material
  language: pt-BR
  favicon: assets/logo.png
  logo: assets/logo.png
  icon: 
   repo: fontawesome/brands/github
  font: 
    text: Roboto
  features:
  - navigation.instant
  - navigation.section
  - navigation.path
  - navigation.top
  - navigation.tabs
  - navigation.tabs.sticky

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro
      # primary: deep purple
      # accent: purple 
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro
      # primary: deep purple
      # accent: purple

extra_css: [stylesheets/extra.css]


# Page tree
nav: 
  - Início: index.md
  - Atas:
      - Ata 1: atas/Ata_25-09-2023.md
      - Ata 2: atas/Ata_27-09-2023.md
      - Ata 3: atas/Ata_28-09-2023.md
      - Ata 4: atas/Ata_10-10-2023.md
  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao_1.md
      - Apresentação 2: apresentacoes/apresentacao_2.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Processo de Design: planejamento/processo_design.md
      - Sites Avaliados: planejamento/sites_avaliados.md
      - Site Escolhido: planejamento/site_escolhido.md
  - Análise de Requisitos: 
      - Aspectos Éticos: analise_de_requisitos/aspectos_eticos.md
      - Perfil de Usuário: analise_de_requisitos/perfil_de_usuario.md
      - Personas: analise_de_requisitos/personas.md
      - Cenários: analise_de_requisitos/cenarios.md
      - Análise de Tarefas:
        - HTA: analise_de_requisitos/analise_de_tarefas/hta.md
        - GOMS: analise_de_requisitos/analise_de_tarefas/goms.md
      - Características da Plataforma: analise_de_requisitos/caracteristicas.md
      - Principios Gerais de Projeto: analise_de_requisitos/principios_gerais.md
      - Metas de Usabilidade: analise_de_requisitos/metas_de_usabilidade.md
      - Guia de Estilos: analise_de_requisitos/guia_de_estilos.md  

# Extensions
markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
