# Project information
site_name: Dominio Público
site_author: Grupo 4
site_description: >-
  Documentação para do projeto de avaliação de interface do site Dominio Publico realizado na disciplina de Interação Humano Computador na Universidade de Brasília


# Repository
repo_url: https://github.com/Interacao-Humano-Computador/2023.2-Dominio-Publico
repo_name: 2023.2-dominio-publico


# Configuration
docs_dir: docs
theme: 
  name: material
  language: pt-BR
  favicon: assets/logo.png
  logo: assets/logo.png
  icon: 
   repo: fontawesome/brands/github
  font: 
    text: Roboto
  features:
  - navigation.instant
  - navigation.section
  - navigation.path
  - navigation.top
  - navigation.tabs
  - navigation.tabs.sticky

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro
      # primary: deep purple
      # accent: purple 
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro
      # primary: deep purple
      # accent: purple

extra_css: [stylesheets/extra.css]


# Page tree
nav: 
  - Início: index.md
  - Atas:
      - Ata 1: atas/Ata_25-09-2023.md
      - Ata 2: atas/Ata_27-09-2023.md
      - Ata 3: atas/Ata_28-09-2023.md
      - Ata 4: atas/Ata_10-10-2023.md
      - Ata 5: atas/Ata_26-10-2023.md
      - Ata 6: atas/Ata_21-11-2023.md
  - Apresentações:
      - Apresentação 1: apresentacoes/apresentacao_1.md
      - Apresentação 2: apresentacoes/apresentacao_2.md
      - Apresentação 3: apresentacoes/apresentacao_3.md
      - Apresentação 4: apresentacoes/apresentacao_4.md
      - Apresentação 5: apresentacoes/apresentacao_5.md
      - Apresentação 6.1: apresentacoes/apresentacao_6.1.md
      - Apresentação 7: apresentacoes/apresentacao_7.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Processo de Design: planejamento/processo_design.md
      - Sites Avaliados: planejamento/sites_avaliados.md
      - Site Escolhido: planejamento/site_escolhido.md
  - Análise de Requisitos: 
      - Aspectos Éticos: analise_de_requisitos/aspectos_eticos.md
      - Perfil de Usuário: analise_de_requisitos/perfil_de_usuario.md
      - Personas: analise_de_requisitos/personas.md
      - Cenários: analise_de_requisitos/cenarios.md
      - Análise de Tarefas:
        - HTA: analise_de_requisitos/analise_de_tarefas/hta.md
        - GOMS: analise_de_requisitos/analise_de_tarefas/goms.md
      - Características da Plataforma: analise_de_requisitos/caracteristicas.md
      - Principios Gerais de Projeto: analise_de_requisitos/principios_gerais.md
      - Metas de Usabilidade: analise_de_requisitos/metas_de_usabilidade.md
      - Guia de Estilo: analise_de_requisitos/guia_de_estilo.md
  - Design, Avaliação e Desenvolvimento:
      - Nivel 1:
        - Análise de Tarefas: 
          - Planejamento da Avaliação: design_avalaiacao_desenvolvimento/nivel1/analise_de_tarefas/planejamento_avaliacao.md
          - Planejamento do Relato dos Resultados: design_avalaiacao_desenvolvimento/nivel1/analise_de_tarefas/planejamento_relato.md
          - Relato dos resultados: design_avalaiacao_desenvolvimento/nivel1/analise_de_tarefas/relato_resultados.md
        - Storyboard:
          - Planejamento da Avaliação: design_avalaiacao_desenvolvimento/nivel1/storyboard/planejamento_avaliacao.md
          - Planejamento do Relato dos Resultados: design_avalaiacao_desenvolvimento/nivel1/storyboard/planejamento_relato.md
          - Relato dos resultados: design_avalaiacao_desenvolvimento/nivel1/storyboard/relato_resultados.md
          - Storyboards: design_avalaiacao_desenvolvimento/nivel1/storyboard/storyboards.md
      - Nivel 2:
        - Protótipo de Papel: 
          - Planejamento da Avaliação: design_avalaiacao_desenvolvimento/nivel2/prototipo_de_papel/planejamento_avaliacao.md
          - Planejamento do Relato dos Resultados: design_avalaiacao_desenvolvimento/nivel2/prototipo_de_papel/planejamento_relato.md
          - Relato dos resultados: design_avalaiacao_desenvolvimento/nivel2/prototipo_de_papel/relato_resultados.md
      - Nivel 3:
        - Protótipo de Alta Fidelidade: 
          - Planejamento da Avaliação: design_avalaiacao_desenvolvimento/nivel3/prototipo_alta_fidelidade/planejamento_avaliacao.md
          - Planejamento do Relato dos Resultados: design_avalaiacao_desenvolvimento/nivel3/prototipo_alta_fidelidade/planejamento_relato.md
          - Relato dos resultados: design_avalaiacao_desenvolvimento/nivel3/prototipo_alta_fidelidade/relato_resultados.md
          
  - Verificação:
      - Grupo 5:
          - Etapa de Planejamento:
            - Planejamento da Verificação: verficacao/verificacao_grupo_5/etapa_planejamento/planejamento_avaliacao.md
            - Ferramentas: verficacao/verificacao_grupo_5/etapa_planejamento/ferramentas.md
            - Cronograma Planejado: verficacao/verificacao_grupo_5/etapa_planejamento/cronograma_planejado.md
            - Cronograma Executado: verficacao/verificacao_grupo_5/etapa_planejamento/cronograma_executado.md
            - Heat-map: verficacao/verificacao_grupo_5/etapa_planejamento/heat-map.md
            - Sites Avaliados: verficacao/verificacao_grupo_5/etapa_planejamento/sites_avaliados.md
            - Processo de Design: verficacao/verificacao_grupo_5/etapa_planejamento/processo_desing.md
            - Site Escolhido: verficacao/verificacao_grupo_5/etapa_planejamento/site_escolhido.md
          - Etapa de Análise de Requisitos:
            - Planejamento da Verificação: verficacao/verificacao_grupo_5/etapa_analise_requisitos/planejamento_avaliacao.md
            - Perfil do Usuário: verficacao/verificacao_grupo_5/etapa_analise_requisitos/perfil_usuario.md
            - Personas: verficacao/verificacao_grupo_5/etapa_analise_requisitos/personas.md
            - Cenários: verficacao/verificacao_grupo_5/etapa_analise_requisitos/cenarios.md
            - Aspectos Éticos: verficacao/verificacao_grupo_5/etapa_analise_requisitos/aspectos_eticos.md
            - Análise de Tarefas: verficacao/verificacao_grupo_5/etapa_analise_requisitos/analise_tarefas.md
            - Principios e Diretrizes Gerais: verficacao/verificacao_grupo_5/etapa_analise_requisitos/principios_diretrizes.md
            - Metas de Usabilidade: verficacao/verificacao_grupo_5/etapa_analise_requisitos/metas_usabilidade.md
            - Caracteristicas Gerais: verficacao/verificacao_grupo_5/etapa_analise_requisitos/caracteristicas_gerais.md
            - Guia de Estilo: verficacao/verificacao_grupo_5/etapa_analise_requisitos/guia_estilo.md
          - Etapa de Design, Avaliação e Desenvolvimento:
            - Planejamento da Verificação: verficacao/verificacao_grupo_5/etapa_design_avaliacao/planejamento_avaliacao.md
            - Nível 1:
              - Storyboard:
                - Planejamento da Avaliação: verficacao/verificacao_grupo_5/etapa_design_avaliacao/nivel_1/storyboard/planejamento_avaliacao.md
                - Planejamento do Relato dos Resultados: verficacao/verificacao_grupo_5/etapa_design_avaliacao/nivel_1/storyboard/planejamento_relato.md
                - Relato dos resultados: verficacao/verificacao_grupo_5/etapa_design_avaliacao/nivel_1/storyboard/relato_resultados.md
                - Nossos Storyboards: verficacao/verificacao_grupo_5/etapa_design_avaliacao/nivel_1/storyboard/storyboards.md
              - Análise de Tarefas: 
                - Planejamento da Avaliação: verficacao/verificacao_grupo_5/etapa_design_avaliacao/nivel_1/analise_tarefas/planejamento_avaliacao.md
                - Planejamento do Relato dos Resultados: verficacao/verificacao_grupo_5/etapa_design_avaliacao/nivel_1/analise_tarefas/planejamento_relato.md
                - Relato dos resultados: verficacao/verificacao_grupo_5/etapa_design_avaliacao/nivel_1/analise_tarefas/relato_resultados.md
            - Nível 2:
                - Protótipo de Papel: 
                  - Planejamento da Avaliação: verficacao/verificacao_grupo_5/etapa_design_avaliacao/nivel_2/prototipo_de_papel/planejamento_avaliacao.md
                  - Planejamento do Relato dos Resultados: verficacao/verificacao_grupo_5/etapa_design_avaliacao/nivel_2/prototipo_de_papel/planejamento_relato.md
                  - Relato dos resultados: verficacao/verificacao_grupo_5/etapa_design_avaliacao/nivel_2/prototipo_de_papel/relato_resultados.md
# Extensions
markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
